### ISSUE TITLE
0.3.0-BETA - fishing is prevented in singleplayer and multiplayer

### ISSUE THREAD

**Issue by katubug** [Luligabi1/MagicFungi#11]
Using Fabric 0.11.6, Fabric API 0.40.0, and magicfungi-0.3.0-BETA. Fishing doesn't work, right clicking near water with a rod will result in it immediately being pulled back. It does not seem to fully extend at all.

First noticed it on multiplayer server, where it happened for multiple folks. Then, managed to narrow it down to just this mod causing the issue. Finally, I loaded an isolated instance with just this mod and Fabric/API, and it still occurs.

**Comment by katubug** [comment]
Update: shearing bee nests and vanilla sheep is also broken! Shearing modded sheep is fine somehow.

**Comment by Luligabi1** [comment]
Found the culprit - the external lib used to add the custom shield is breaking a lot of other vanilla items. I'll temporarily remove it on subsequent releases, expect one in  the next few days. Sorry for the inconvenience!

**Comment by katubug** [comment]
Awesome, I'll be looking out for it! Thanks!
