### ISSUE TITLE
Morbus Scythe Unenchantable

### ISSUE THREAD

**Issue by milkev** [Luligabi1/MagicFungi#19]
You cant put looting, sharpness, sweeping edge, etc on a morbus scythe

**Comment by milkev** [comment]
it also cant do aoe attacks

**Comment by Luligabi1** [comment]
I think i know why that is - will try to make a fix for it on the next update.

Also, what are "aoe attacks"?

**Comment by milkev** [comment]
[https://minecraft.fandom.com/wiki/Sword#Sweep_attack](https://minecraft.fandom.com/wiki/Sword#Sweep_attack) this. it doesnt do much damage on its own but it can do quite a bit of damage with sweeping edge

**Comment by Luligabi1** [comment]
Upon closer inspection, this behavior is intended, therefore there's nothing to fix. Morbus Scythe is meant to be a form of a "combat hoe" and thus can only receive the same enchantments as one (meaning only unbreakable and mending). If you wish to have sword enchantments and AOE attacks, consider crafting a Impetus Sword.
