### ISSUE TITLE
healt boost doesn't work

### ISSUE THREAD

**Issue by thin0paper** [Luligabi1/MagicFungi#32]
The command /effect give @p health_boost (time) (amplifier) does not work. Also mods (for example magick: potions and pearls) in which there are health boost potions don't work. There could also be other effects that do not work but so far ive only encountered this one. I think this perhaps has something to do with the magical fungi set giving a healt boost. (sorry if i spelt anything wrong, english isnt my first language)

**Comment by Luligabi1** [comment]
I'll investigate this tomorrow, thanks for the report! 

> sorry if i spelt anything wrong, english isnt my first language

Neither is it my first, don't be apologetic about it 😄

**Comment by Luligabi1** [comment]
Can reproduce; I'll start working on a fix soon.

**Comment by Luligabi1** [comment]
Hey @thin0paper , I've just pushed a fix for this issue. Thanks again for reporting!

Get it here:

- [CurseForge (1.18.x)](https://www.curseforge.com/minecraft/mc-mods/magic-fungi/files/3578196)
- [CurseForge (1.17.1)](https://www.curseforge.com/minecraft/mc-mods/magic-fungi/files/3578214)
