### ISSUE TITLE
[Feature Request] Biome Selection

### ISSUE THREAD

**Issue by itsdinkd** [Luligabi1/MagicFungi#40]
Due to incompatibilities with terralith, It would be wonderful if you created a feature in the config that allows the modpack developer to specify and target which biome to spawn in morbius mushrooms as well as anything else that would normally only be in a magicfungi biome. 

This would solve the issue with Terralith, and also allow for a major part of the mod to be used, which is the morbius feature and items. I have your mod in my modpack, Another Quality Modpack 3, and I'm trying to get around the whole terralith thing for morbius, but it just seems impossible to do without being able to target a biome. I could modify recipes, yes, but that doesn't seem very fun for players versus hunting for mrobius mushrooms.

**Comment by Luligabi1** [comment]
Sorry, but that won't happen. Much of the planned features on upcoming versions rely not only on the Morbus Mushroom, but the Host Biome itself; implementing this would add an unnecessary layer of complexity that I'm not wishing to maintain.

**Comment by itsdinkd** [comment]
Isn't that complexity worth dealing with to increase the range of your audience size of players / packs who use your mod? just saying.

**Comment by itsdinkd** [comment]
@Luligabi1 so https://www.curseforge.com/minecraft/mc-mods/terrablender-fabric Terrablender came out for fabric which was made to make Biomes o Plenty compatible with terralith. Can you use this library with Magic Fungi to spawn in the morbius biome?

**Comment by Luligabi1** [comment]
> @Luligabi1 so https://www.curseforge.com/minecraft/mc-mods/terrablender-fabric Terrablender came out for fabric which was made to make Biomes o Plenty compatible with terralith. Can you use this library with Magic Fungi to spawn in the morbius biome?

I'm currently watching progress for another biome API, but it's currently too unstable to be used here. Whenever I'm satified with the stability of an API, I'll readd the Host Biome with it.

**Comment by itsdinkd** [comment]
But is that other API made to be compatible with world Gen mods/datapacks like Terralith? I'm just going to remove Magic Fungi from my modpack, Another Quality Modpack 2. If you ever 
- add a feature that makes your host biome work with terralith via API, 
- allow whitelist biomes to spawn the morbius mushroom in, or
- create a structure that spawns morbius mushroom in it 

please let me know and I'll add it back.

Thanks!
