### ISSUE TITLE
add a config to disable the book when spawning

### ISSUE THREAD

**Issue by Chuunkyz** [Luligabi1/MagicFungi#41]
THIS

**Comment by Luligabi1** [comment]
Not sure how this could be done as the book is given via a datapack. If you're able to override these 2 files, the book won't be given:

- [Loot table](https://github.com/Luligabi1/MagicFungi/blob/1.18/src/main/resources/data/magicfungi/loot_tables/first_join_book.json)
- [Advancement](https://github.com/Luligabi1/MagicFungi/blob/1.18/src/main/resources/data/magicfungi/advancements/first_join_book.json)
