### ISSUE TITLE
no modded ores in host biome

### ISSUE THREAD

**Issue by Chuunkyz** [Luligabi1/MagicFungi#45]
the ores depending on biome category are still generating, but not the others (like tech reborn or mi)
also this is not a terrablender problem (https://github.com/Glitchfiend/TerraBlender/issues/25)

**Comment by Luligabi1** [comment]
This seems to be a Fabric bug when ore generation is done via `BiomeModifications#create` rather than `BiomeModifications#addFeature`. [This PR at Fabric API aims to fix this glitch when it's approved](https://github.com/FabricMC/fabric/pull/1966). If it doesn't, please reopen this issue

**Comment by Luligabi1** [comment]
Fabric API `0.46.3+1.18` has been released with an fix for this issue.
