### ISSUE TITLE
Not compatible with FabricSeasons

### ISSUE THREAD

**Issue by TheButterbrotMan** [Luligabi1/MagicFungi#46]
When i add MagicFungi in my modpack, the weather seems bugged. At some places it is snowing, at some raining. If i remove MagicFungi its everywhere raining (like it should)

**Comment by Luligabi1** [comment]
I don't understand what the issue is here. Weather on the Host Biome works like the desert biomes do, with no rain or snow. Is it somehow affecting other biomes?

**Comment by TheButterbrotMan** [comment]
So, my world is on Summer. When i add magic fungi, random places starts snowing.

**Comment by Luligabi1** [comment]
that's more likely to be an issue with Fabric Seasons and/or mod incompatibility.  Magic Fungi does no altering to how other biomes' weather behave.

**Comment by Luligabi1** [comment]
As no new information has been discovered related to this issue, I'm closing it. If anything else is found, please reopen it!
